
[package]
authors = ["jssite@googlegroups.com"]
edition = "2024"
name    = "blake3"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi        = "3.5.2"
napi-derive = "3.3.3"

[build-dependencies]
napi-build = "2"

[profile.release]
lto   = true
strip = "symbols"
